parameters:
    app.resources_dir: '%env(RESOURCES_DIR)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
